repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    name: Run type checks
    args: ["--ignore-missing-imports"]
    additional_dependencies: ["types-requests"]
- repo: local
  hooks:
  - id: no-todos
    name: Forbid TODOs
    entry: "TODO"
    language: pygrep
    types: [python]
- repo: local
  hooks:
  - id: gitchangelog
    language: system
    always_run: true
    pass_filenames: false
    name: Generate changelog
    entry: bash -c "gitchangelog > CHANGELOG.md"
    stages: [commit]
